#!/usr/bin/env python3
"""Generate assets/schema_strictness.md from live scans.

The file was hand-maintained and needed three corrections in one week: the
3-of-5 tool cap, the deleted server averages, and `required[0]` being described
as the tool. It was about to need a fourth when optional fields started being
probed. It is the standing counterexample to this project's own rule that an
artifact nothing regenerates goes stale behind a shipped change.

    uv run python tools/schema_strictness.py            # print
    uv run python tools/schema_strictness.py --write    # rewrite the asset

Needs network: these are live hosted servers. `--check` exits 1 when the
committed file disagrees with a fresh generation, which is what the test uses
when the assets directory is present.
"""
from __future__ import annotations

import argparse
import asyncio
import pathlib
import sys

from ratemyagent.probes.contract import (
    case_count,
    declarable_violations,
    plan_coverage,
    schema_strictness,
)
from ratemyagent.targets import MCPTarget

ASSET = pathlib.Path(__file__).resolve().parents[1] / "assets" / "schema_strictness.md"

SERVERS: tuple[tuple[str, str], ...] = (
    ("docs.statsig.com/api/mcp", "https://docs.statsig.com/api/mcp"),
    ("api.htagai.com/.../htag-docs",
     "https://api.htagai.com/mcp/v1/servers/htag-docs/mcp"),
    ("worldbank.caseyjhand.com", "https://worldbank.caseyjhand.com/mcp"),
    ("cpsc-recalls.caseyjhand.com", "https://cpsc-recalls.caseyjhand.com/mcp"),
)


async def survey_all() -> list[tuple[str, list[dict], float | None]]:
    """Every server, in one event loop. See the note in `main`."""
    surveyed = []
    for label, uri in SERVERS:
        rows, strictness = await survey(uri)
        surveyed.append((label, rows, strictness))
    return surveyed


async def survey(uri: str) -> tuple[list[dict], float | None]:
    target = MCPTarget(uri, timeout_s=30)
    await target.setup()
    try:
        probed = plan_coverage(target.list_tools(), limit=3, allow_mutating=False).probed
        rows = []
        for tool in probed:
            schema = tool.input_schema or {}
            required = list(schema.get("required") or [])
            properties = schema.get("properties") or {}
            rows.append({
                "tool": tool.name,
                "declarable": len(declarable_violations(tool)),
                # `additional_properties` must reach both, or they walk the
                # same declaration differently: `declarable_violations` reads
                # the schema and counts `extra_param` when it is forbidden,
                # while a `case_count` without the flag never emits it. That
                # printed `1/0` for `worldbank_list_topics` -- one violation out
                # of zero possible cases -- in a published asset. Third site of
                # the two-walks bug, and this one was introduced by the fix for
                # the first two.
                "cases": case_count(
                    required, properties,
                    additional_properties=schema.get("additionalProperties"),
                ),
                "required": len(required),
                "optional": len([k for k in properties if k not in required]),
            })
        return rows, schema_strictness(probed)
    finally:
        await target.teardown()


def render(surveyed: list[tuple[str, list[dict], float | None]]) -> str:
    lines = [
        "# Schema strictness across scanned MCP servers",
        "",
        "**Generated by `tools/schema_strictness.py`. Do not edit by hand.**",
        "",
        "Of the cases the contract probe sends a tool, how many does its schema",
        "actually forbid? Computed from the declarations alone, no extra calls.",
        "",
        "Every declared field is counted, required and optional alike. Before",
        "0.1.19 only required fields were probed or counted, so a tool declaring",
        "five typed optional parameters reported that its schema forbids one",
        "thing.",
        "",
        "**Tool level is the unit.** A server average mixes \"nothing to declare\"",
        "with \"declined to declare\", and that distinction is the whole metric.",
        "",
        "| server | tool | declarable | required | optional |",
        "|---|---|---:|---:|---:|",
    ]
    for label, rows, _ in surveyed:
        for index, row in enumerate(rows):
            server = f"`{label}`" if index == 0 else ""
            lines.append(
                f"| {server} | `{row['tool']}` | "
                f"**{row['declarable']}/{row['cases']}** | "
                f"{row['required']} | {row['optional']} |"
            )
    lines.extend([
        "",
        "Server-level figures are derived and reported only for sorting a survey.",
        "Do not quote one as a property of a server.",
        "",
        "| server | strictness |",
        "|---|---:|",
    ])
    for label, _, strictness in surveyed:
        shown = "n/a" if strictness is None else f"{strictness:.2f}"
        lines.append(f"| `{label}` | {shown} |")
    lines.extend([
        "",
        "Only the first three read-only tools of each server are probed, so these",
        "describe those tools rather than the server. Mutating and unclassified",
        "tools are excluded, and the cap is not configurable from the CLI yet.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    # One event loop for all of them, which only became possible in 0.1.20:
    # until then a second `MCPTarget.setup()` was cancelled by scope state the
    # first teardown left behind. This tool needing the workaround is what
    # turned that from a NextSteps note into a release.
    surveyed = asyncio.run(survey_all())

    rendered = render(surveyed)
    if args.write:
        ASSET.write_text(rendered)
        print(f"wrote {ASSET}")
        return 0
    if args.check:
        if not ASSET.exists():
            print("asset missing")
            return 1
        if ASSET.read_text().strip() != rendered.strip():
            print("assets/schema_strictness.md is stale; rerun with --write")
            return 1
        print("up to date")
        return 0
    print(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
